### ISSUE TITLE
Consider merging with zero-to-nix.com

### ISSUE THREAD

**Issue by ostrolucky** [mimoo/nixbyexample#2]
Hi! I am new in Nix, looking for resources for learning Nix and your project is one of the ones I've found. I really like your initiative, unfortunately it was quite short. But I have also found https://zero-to-nix.com/ and since I've noticed your project is not that active and you are looking for contributors, I was thinking to try to suggest to merge forces? I don't know if you know that project, but I think they have the same goal.

**Comment by mimoo** [comment]
Thanks for the suggestion but I think there's different enough to keep this project up, as this is supposed to be a much simpler approach (the other landing page is quite overwhelming)
